<?php

namespace AppBundle\Repository;

/**
 * PoketmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoketmanRepository extends \Doctrine\ORM\EntityRepository
{
}
